# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-27 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shikigami',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=b'')),
                ('shikigamiName', models.CharField(max_length=200)),
                ('shikigamiLocation', models.CharField(max_length=200)),
            ],
        ),
    ]
