# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20180228_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shikigami',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
