# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-28 02:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20180228_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shikigami',
            old_name='shikigamiName',
            new_name='shikigamiJapName',
        ),
        migrations.AddField(
            model_name='shikigami',
            name='shikigamiVietName',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
